dist:
  name: otelcol-dev
  description: "Basic OTel Collector distribution for Developers"
  output_path: ./Vs_Maps_Exporter


exporters:
  - gomod: "github.com/Suraj-Shivagange/VS_Exporter v0.0.0"
    path: "../VS_Exporter"


  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.62.0
    
    
receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.62.0




