receivers:
  otlp:
    protocols:
      grpc:

processors:


exporters:
  kafka:
    brokers:
      - "localhost:19092"
    topic: spans
    protocol_version: 2.0.0
    encoding: otlp_json

        
     

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [kafka]
